language: java
sudo: false
deploy:
  provider: script
  script: "mvn deploy -q -DskipTests=true"
  skip_cleanup: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ada7bbc05b2a99cff40
    on_success: change
    on_failure: always
    on_start: never
